const allActionTypes = {
  IS_USER_AUTHORIZED: "IS_USER_AUTHORIZED",
  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_USER_ALL_SESSIONS: "LOGOUT_USER_ALL_SESSIONS",
  USER_AUTH_ENDED: "USER_AUTH_ENDED",
  FAILED_TO_FETCH: "FAILED_TO_FETCH",
  NEW_ACCESS_TOKEN: "ACCESS_TOKEN",
  ERROR_NEW_ACCESS_TOKEN: "ERROR_NEW_ACCESS_TOKEN",
  LOGIN_ACCESS_TOKEN: "LOGIN_ACCESS_TOKEN",
  HOOK_ACCESS_TOKEN: "HOOK_ACCESS_TOKEN",
};
export default allActionTypes;

export const searchBarTypes = {
  SEARCH_PASSWORD: "SEARCH_PASSWORD",
};

export const userInfoTypes = {
  NAME_AND_EMAIL: "NAME_AND_EMAIL",
};
